benchmark_root: /scratch/mdorazi/Skill_Boundary_Detector/tools/lerobot-libero/libero/libero
bddl_files: /scratch/mdorazi/Skill_Boundary_Detector/tools/lerobot-libero/libero/libero/bddl_files
init_states: /scratch/mdorazi/Skill_Boundary_Detector/tools/lerobot-libero/libero/libero/init_files
datasets: /scratch/mdorazi/Skill_Boundary_Detector/tools/lerobot-libero/libero/datasets
assets: /scratch/mdorazi/Skill_Boundary_Detector/tools/lerobot-libero/libero/libero/assets
