benchmark_root: /data1/dohyeon/Skill_Boundary_Detector/tools/lerobot-libero/libero/libero
bddl_files: /data1/dohyeon/Skill_Boundary_Detector/tools/lerobot-libero/libero/libero/bddl_files
init_states: /data1/dohyeon/Skill_Boundary_Detector/tools/lerobot-libero/libero/libero/init_files
datasets: /data1/dohyeon/Skill_Boundary_Detector/tools/lerobot-libero/libero/datasets
assets: /data1/dohyeon/Skill_Boundary_Detector/tools/lerobot-libero/libero/libero/assets
