########################################################
########################################################

# dataset:
#   skillvla_root: skillvla_dataset
#   source: libero_90_full_full
#   run: FSQ333_contrastive_2000_pt_grounded_fov_rand
#   relabeled: ""

# transition_randomization:
#   enabled: true
#   early_start_pmax: 5
#   late_start_pmax: 5
#   early_end_pmax: 5
#   late_end_pmax: 5
#   distribution: uniform

# run:
#   common_suffix: "rand5_uniform"

# ########################################################

# dataset:
#   skillvla_root: skillvla_dataset
#   source: libero_90_full_full
#   run: FSQ333_contrastive_2000_pt_grounded_fov_rand
#   relabeled: ""

# transition_randomization:
#   enabled: true
#   early_start_pmax: 5
#   late_start_pmax: 5
#   early_end_pmax: 5
#   late_end_pmax: 5
#   distribution: half_normal

# run:
#   common_suffix: "rand5_norm"

# ########################################################
# ########################################################

# dataset:
#   skillvla_root: skillvla_dataset
#   source: libero_90_full_full
#   run: FSQ333_contrastive_2000_pt_grounded_fov_rand
#   relabeled: ""

# transition_randomization:
#   enabled: true
#   early_start_pmax: 15
#   late_start_pmax: 15
#   early_end_pmax: 15
#   late_end_pmax: 15
#   distribution: uniform

# run:
#   common_suffix: "rand15_uniform"

# ########################################################

# dataset:
#   skillvla_root: skillvla_dataset
#   source: libero_90_full_full
#   run: FSQ333_contrastive_2000_pt_grounded_fov_rand
#   relabeled: ""

# transition_randomization:
#   enabled: true
#   early_start_pmax: 15
#   late_start_pmax: 15
#   early_end_pmax: 15
#   late_end_pmax: 15
#   distribution: half_normal

# run:
#   common_suffix: "rand15_norm"

# ########################################################
# ########################################################

# dataset:
#   skillvla_root: skillvla_dataset
#   source: libero_90_full_full
#   run: FSQ333_contrastive_2000_pt_grounded_fov_rand
#   relabeled: ""

# transition_randomization:
#   enabled: true
#   early_start_pmax: 20
#   late_start_pmax: 20
#   early_end_pmax: 20
#   late_end_pmax: 20
#   distribution: uniform

# run:
#   common_suffix: "rand20_uniform"

# ########################################################

# dataset:
#   skillvla_root: skillvla_dataset
#   source: libero_90_full_full
#   run: FSQ333_contrastive_2000_pt_grounded_fov_rand
#   relabeled: ""

# transition_randomization:
#   enabled: true
#   early_start_pmax: 20
#   late_start_pmax: 20
#   early_end_pmax: 20
#   late_end_pmax: 20
#   distribution: half_normal

# run:
#   common_suffix: "rand20_norm"

#######################################################
#### Previous #########################################
#######################################################
dataset:
  skillvla_root: skillvla_dataset
  source: libero_90_full_full
  run: FSQ333_contrastive_2000_pt_grounded_fov_new
  relabeled: ""

transition_randomization:
  enabled: true
  early_start_pmax: 15
  late_start_pmax: 10
  early_end_pmax: 15
  late_end_pmax: 10
  distribution: half_normal

run:
  common_suffix: ""
#######################################################
#######################################################
#######################################################

warm_start:
  pi_base: models/pi05_base
  tokenizer: models/paligemma-3b-pt-224-tokenizer
